// Generated by `pnpm --filter @wavr/schema gen` from src/descriptions.md.
// Hand-edited during bootstrap; run `gen` once descriptions.md authoring starts.
//
// Every schema symbol that should carry a .describe() must have a key here.
// The walker-invariant test (test/schema.test.ts) fails if any leaf is missing.

export const DESCRIPTIONS = {
  // Primitives
  "RGBColor": "Linear RGB color, each channel 0–1.",
  "ColorSpace": "Color space the RGBColor values are authored in. 'linear' is the current convention.",
  "GradientType": "Base shader that generates this layer. `image` requires a companion imageData payload (EditorState.layerExtensions).",
  "BlendMode": "Photoshop-compatible layer blend mode. Ports 1:1 from packages/core/src/layers.ts.",
  "Shape3DKind": "Projection surface for the 3D-shape effect.",

  // Layer
  "LayerConfig": "A single gradient layer composited into the final image.",
  "LayerConfig.type": "Base shader for this layer.",
  "LayerConfig.colors": "2–8 colors sampled across the gradient.",
  "LayerConfig.speed": "Animation speed multiplier. 0 = frozen.",
  "LayerConfig.complexity": "Shape detail / fBm octaves.",
  "LayerConfig.scale": "Pattern zoom. <1 = larger features.",
  "LayerConfig.distortion": "Noise displacement of UVs.",
  "LayerConfig.opacity": "Layer opacity when composited.",
  "LayerConfig.blendMode": "How this layer composites onto the layer beneath.",
  "LayerConfig.depth": "Parallax depth. Negative = behind.",

  // Root
  "GradientConfig": "Root Wavr gradient configuration. Shared by the editor, runtime, URL codec, and MCP agent tools.",
  "GradientConfig.version": "Schema version. Bump via migrate().",
  "GradientConfig.colorSpace": "Color space of RGBColor values throughout this config.",
  "GradientConfig.layers": "Ordered layer stack, 1–4 layers. Bottom to top.",
  "GradientConfig.brightness": "Linear luminance multiplier applied after tone mapping.",
  "GradientConfig.saturation": "Saturation scalar. 0 = greyscale, 1 = identity, 2 = oversaturated.",
  "GradientConfig.grain": "Per-frame film-grain amount.",
  "GradientConfig.vignette": "Darkens edges toward the frame border.",
  "GradientConfig.chromaticAberration": "Per-channel UV offset strength.",
  "GradientConfig.hueShift": "Hue rotation in degrees, -180 to 180.",
  "GradientConfig.domainWarp": "Global UV noise warp amount.",
  "GradientConfig.radialBlur": "Radial blur strength from the center.",
  "GradientConfig.mouseReact": "How strongly mouse position modulates animation.",
  "GradientConfig.oklabEnabled": "Blend colors in OKLab space for more perceptual gradients.",
  "GradientConfig.toneMapMode": "Tone mapping: 0=none, 1=ACES, 2=Reinhard, 3=Filmic.",

  // Effect groups — noun-phrase descriptors
  "NoiseEffect": "Fractal-noise overlay added to the composited gradient.",
  "NoiseEffect.enabled": "Whether the effect runs.",
  "NoiseEffect.intensity": "Blend amount of the noise overlay.",
  "NoiseEffect.scale": "Spatial frequency of the noise.",

  "BloomEffect": "Gaussian-approx bloom on highlights.",
  "BloomEffect.enabled": "Whether bloom runs.",
  "BloomEffect.intensity": "Bloom strength.",

  "BlurEffect": "Full-frame separable Gaussian blur.",
  "BlurEffect.enabled": "Whether blur runs.",
  "BlurEffect.amount": "Blur kernel size, normalized.",

  "CurlEffect": "Curl-noise UV distortion.",
  "CurlEffect.enabled": "Whether curl noise runs.",
  "CurlEffect.intensity": "Displacement strength.",
  "CurlEffect.scale": "Spatial frequency of the curl field.",

  "KaleidoscopeEffect": "Mirrored radial repetition.",
  "KaleidoscopeEffect.enabled": "Whether kaleidoscope runs.",
  "KaleidoscopeEffect.segments": "Number of mirror segments.",
  "KaleidoscopeEffect.rotation": "Rotation offset in degrees.",

  "ReactionDiffusionEffect": "Gray–Scott reaction-diffusion pattern overlay.",
  "ReactionDiffusionEffect.enabled": "Whether reaction-diffusion runs.",
  "ReactionDiffusionEffect.intensity": "Blend amount.",
  "ReactionDiffusionEffect.scale": "Spatial frequency.",

  "PixelSortEffect": "Row-sorted pixels above a brightness threshold.",
  "PixelSortEffect.enabled": "Whether pixel sort runs.",
  "PixelSortEffect.intensity": "Sort contribution.",
  "PixelSortEffect.threshold": "Brightness threshold that triggers sorting.",

  "FeedbackEffect": "Frame-to-frame feedback trail.",
  "FeedbackEffect.enabled": "Whether feedback runs.",
  "FeedbackEffect.decay": "Fraction of the previous frame retained.",

  "AsciiEffect": "Rasterize output to an ASCII character grid.",
  "AsciiEffect.enabled": "Whether ASCII rendering runs.",
  "AsciiEffect.size": "Character cell size in pixels.",

  "DitherEffect": "Ordered-Bayer dither post-pass. Different from the Step 1 blue-noise anti-banding pass.",
  "DitherEffect.enabled": "Whether dithering runs.",
  "DitherEffect.size": "Bayer matrix cell size.",

  "ParallaxEffect": "Mouse-driven parallax offset per layer.",
  "ParallaxEffect.enabled": "Whether parallax runs.",
  "ParallaxEffect.strength": "Parallax offset strength.",

  "Shape3DEffect": "Project the 2D gradient onto a 3D surface.",
  "Shape3DEffect.enabled": "Whether 3D projection runs.",
  "Shape3DEffect.shape": "Projection surface.",
  "Shape3DEffect.perspective": "Camera field-of-view multiplier.",
  "Shape3DEffect.rotationSpeed": "Rotation speed of the 3D shape.",
  "Shape3DEffect.zoom": "Camera distance.",
  "Shape3DEffect.lighting": "Directional-light contribution.",

  "MeshDistortionEffect": "Animated vertex-mesh displacement.",
  "MeshDistortionEffect.enabled": "Whether mesh distortion runs.",
  "MeshDistortionEffect.displacement": "Peak displacement amplitude.",
  "MeshDistortionEffect.frequency": "Spatial frequency of the displacement field.",
  "MeshDistortionEffect.speed": "Displacement animation speed.",

  "RippleEffect": "Concentric ripple distortion.",
  "RippleEffect.enabled": "Whether ripples run.",
  "RippleEffect.intensity": "Ripple amplitude.",

  "GlowEffect": "Soft outer glow around bright regions.",
  "GlowEffect.enabled": "Whether glow runs.",
  "GlowEffect.intensity": "Glow brightness.",
  "GlowEffect.radius": "Glow spread, normalized to frame width.",

  "CausticEffect": "Simulated caustic light patterns.",
  "CausticEffect.enabled": "Whether caustics run.",
  "CausticEffect.intensity": "Caustic contribution.",

  "LiquifyEffect": "Swirled liquid-like UV warping.",
  "LiquifyEffect.enabled": "Whether liquify runs.",
  "LiquifyEffect.intensity": "Warp strength.",
  "LiquifyEffect.scale": "Spatial frequency of the warp field.",

  "TrailEffect": "Motion trail on animated values.",
  "TrailEffect.enabled": "Whether trail runs.",
  "TrailEffect.length": "Trail length as a fraction of the previous frame retained.",
  "TrailEffect.width": "Trail width.",

  "RealBloomEffect": "Physically-correct bloom pass. Was top-level `realBloomEnabled` in V1.",
  "RealBloomEffect.enabled": "Whether real-bloom runs.",

  "DebandEffect": "Blue-noise anti-banding pass applied before final output. Adds sub-pixel noise to hide 8-bit color banding. On by default.",
  "DebandEffect.enabled": "Whether the deband pass runs. On by default — turn off only for pixel-perfect posterized output.",
  "DebandEffect.strength": "Dither amplitude, in output LSBs. 1 = baseline anti-banding.",
} as const;

export type DescriptionKey = keyof typeof DESCRIPTIONS;

/**
 * Apply a canonical description to a Zod schema. Throws at module-load if the
 * key is missing, so a typo or forgotten entry fails the build rather than
 * silently producing an undescribed field.
 *
 * Named `d` (not `describe`) to avoid colliding with vitest's `describe`.
 */
export function d<T extends { describe: (s: string) => T }>(
  key: DescriptionKey,
  schema: T,
): T {
  const text = DESCRIPTIONS[key];
  if (!text) throw new Error(`@wavr/schema: missing description for '${key}'`);
  return schema.describe(text);
}
